name: Build and Test Next.JS Application

on:
  push:
    branches:
      - main
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checksout Repo
        uses: actions/checkout@v2

      - name: Setup Node JS
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Cache Packages and Source Code
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js') }}
          # If source files changed but packages didn't, rebuild from a prior cache. 
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - run: npm install
      - run: npm run build

      - name: Commit updated build files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated publish