name: Build and Test Next.JS Application

on:	push

jobs:
	build-project:
		name: Build Application
		runs-on: ubuntu-latest
		steps:
			- name: Checkout Code
			  uses: actions/checkout@v2
			- name: Install NPM dependencies
			  uses: npm install
			- name: Build Static Website
			  uses: npm run build
