name: Node.js Build-Test-Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node JS
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
    
    - name: Build Project
      run: npm run build --if-present

    # run npm test, lint, export, etc.