name: Node.js Build-Test-Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node JS
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
    
    - name: Build Project
      run: npm run build --if-present
    
    - name: Run Cypress Test Suite
      run: npm run cypress:run:reporter
      continue-on-error: true

    - name: Copy Test Results and Videos
      run: |
        mkdir public
        cp -r cypress/videos public/videos
        cp -r test-runs/reports public/reports

    - name: Generate HTML Report
      run: npm run report:generate
    
    - name: Publish Test Report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public