name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: npm test
    - run: npm export