name: Node.js Build-Test-Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Cache Node Modules and Next Folder
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Setup Node ${{ matrix.node-version }} and Cache
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          '**/package-lock.json'

    - name: Install Dependencies
      run: npm i
    
    - name: Build Project
      run: npm run build --if-present
